version: '3'
services:
  node-test:
    image: node:latest
    environment: 
      - NODE_ENV=test
    restart: always
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: quillhash-test
    ports: 
      - "8000:8000"