version: "3"
services:
  godutch-node:
    container_name: godutch
    build:
      context: .
      dockerfile: dockerfile
    image: node:alpine
    environment: 
      - NODE_ENV=production
    restart: always
    ports:
      - "8000:8000"