version: "3"
services:
  node:
    container_name: quillhash
    build:
      context: .
      dockerfile: dockerfile
    image: node:latest
    environment: 
      - NODE_ENV=production
    restart: always
    ports:
      - "8000:8000"
    command: npm start